### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small and useless PR adds a button to get your app on F-Droid 👍 It's also ready to publish a Google Play button if you upload it on this store ;)

### CODE REVIEW

**Comment by toxtox** [comment]
Sorry for my delayed response, I was quite busy the last days

Thanks for your Commit. Yes, you are right, an **F-Droid button** makes sense in the **_README.md_**. 
But unfortunately until today nobody has published the app on google playstore yet.

**Maybe you have an google playstore account and could publish the app on google playstore?**

You are allowed to use/copy all informations/screeshots from https://f-droid.org/en/packages/com.toxtox.philosopherstonewidget/ for google playstore publishing.
If google wants to have money for publishing I will give you the money back in **PHS**.

**Comment by Poussinou** [comment]
No problem, just answer when you have time ;)
I don't have a google play store account yet, but I'm planning to open open one in the future. It costs 25$, you would like to share the cost with me? Otherwise I can open it now on my own, if you allow me to publish your app, I'll do it with pleasure ;)
By the way, if you share the cost with me in PHS, it would allow me to discover the world of cryptocurrencies, I'm not used to that kind of things^^

**Comment by toxtox** [comment]
Sounds great! I will pay your costs completely. Just give me one of your PHS-incomming addresses and I will send you **1000PHS** as soon as I get your PHS-address (The rest you can use for buying coffee, pizza and so on :-)
As I have written in f-droid https://f-droid.org/en/packages/com.toxtox.philosopherstonewidget/ the app is licenced by MIT-licence and:
_"Everyone is welcome to publish the '''SimplePhilosopherstoneWidget''' (including the description above) on other APP-Stores, too (e.g. google playstore and others...)"_
So you are allowed to take everything of f-droid (apk-binary-file, descriptions, screeshots and so on) and put it on google play store. If you have some own ideas, feel free to change or add something.  :-)

Thank you and good luck!

**Comment by toxtox** [comment]
@Poussinou  
Thank you for your pull request. F-Droid button looks good!
If you need some help for bringing the '''_SimplePhilosopherstoneWidget_''' to google playstore of if you need some more PHS for food and drinks, please let me know. ;-)

**Comment by Poussinou** [comment]
@toxtox Sorry I'm really busy right now, due to some exams at school ❤️ 
I had some problems also with the PHS desktop client. I'll have a look later, in approximately 10 days ;) (after my exams in fact)

By the way, I don't need more PHS for food nor drink, I'm already fat enough 😛 I just want to understand how cryptocurrencies work. For example, how can I convert PHS to euros. Or maybe I will keep my PHS as they are in my (future) PHS wallet, I don't know...
So as I said, I'll do it in a near future, just give some time 👍

**Comment by toxtox** [comment]
Exams have highest priority! Do **not** read this before you have finished your exams !
> how can I convert PHS to euros. 

You can create an account with just a working email address for 2factor authentication and transaction confirmation at https://www.cryptopia.co.nz
Here you can change PHS into BTC and BTC you can change to EUR for example at www.bitcoin.de or many other exchanges.
A good starting point for getting some basic infos/links about PHS might be twitter https://twitter.com/PHS_stone , https://twitter.com/search?q=%24philosopherstones&src=typd or the forum https://bitcointalk.org/index.php?topic=830427.580
website: http://philosopherstones.org/
Win + Mac wallet:
https://github.com/philosopherstonecoin/philosopherstone/releases
Raspberry Pi + Linux 64bit wallets:
https://github.com/toxtox/philosopherstone/releases

**Pull request merged**
